obj - m := cproc.o
// SRC_DIRECTORY=src
// INCLUDE_DIRECTORY=include
// ccflags-y      += -Werror
// ccflags-y      += -I$(src)/include
// ccflags-y      += -I$(src)/$(SRC_DIRECTORY)
// ccflags-y      += -I$(src)/$(INCLUDE_DIRECTORY)